require "isaac.plugins"
require "isaac.alpha"
require "isaac.autotag"
require "isaac.colorscheme"
require "isaac.comfort"
require "isaac.gitsigns"
require "isaac.keymaps"
require "isaac.lsp"
require "isaac.lualine"
require "isaac.neogit"
require "isaac.obsidian"
require "isaac.options"
require "isaac.telescope"
require "isaac.treesitter"
require "isaac.trouble"
require "isaac.which_key"

